### ISSUE TITLE
Link badges in README to their respective labels

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#10]
Link the respective labels to their badges.

You can find the labels <a href="https://github.com/CommunityPro/portfolio-html/labels">here</a>
Copy each label link and use it to wrap their corresponding badge in the README.

### Fix
This is an example of the bug label wrapped with it's link.
```html
<a href="https://github.com/CommunityPro/portfolio-html/labels/bug">
<img src="https://img.shields.io/github/labels/Communitypro/portfolio-html/bug">
</a>
```

- [x] good first issue
- [x] help wanted
- [x] enhancement
- [x] bug

Fix only one, so others can have a go too.

### Badge screenshot
![labels](https://user-images.githubusercontent.com/62628408/149739451-1a632518-af3c-4d21-b704-7ad41be6aff8.png)

**Comment by RishiKumarRay** [comment]
@Evavic44 Can you review

**Comment by Evavic44** [comment]
> @Evavic44 Can you review

Merged. Perfect work! @RishiKumarRay 👍🏽

**Comment by Melford-D** [comment]
well done @RishiKumarRay

**Comment by riyaflix** [comment]
@Evavic44 I have linked PR for bug badge. Can you please review and merge?

**Comment by rishvantsingh** [comment]
I have linked PR for good first issue batch.Can you please review and merge it.

**Comment by ShubhamSaini1585** [comment]
I have updated the help wanted badge. can you please merge the pull request. @Evavic44

**Comment by ShubhamSaini1585** [comment]
Hey @Evavic44 , I have updated the PR. Please check again.

**Comment by Evavic44** [comment]
Awesome job. @ShubhamSaini1585 @RishiKumarRay merged and fixed all. Thanks for your PR. 🌟
