### ISSUE TITLE
[BUG] - HTML is missing h2 closing tag

### ISSUE THREAD

**Issue by NishantChandla** [CommunityPro/portfolio-html#108]
## Describe the bug
There is no closing tag.

## To Reproduce
1. Go to index.html
2. Line 105

## Expected behavior
There should be no errors when parsing HTML

## Screenshot
<img width="564" alt="Screenshot 2022-01-25 at 4 28 45 PM" src="https://user-images.githubusercontent.com/55653617/150964601-2b388579-f5c3-4358-aa77-5a8349c8f4fd.png">

**Comment by Evavic44** [comment]
Lol, oh wow. Thanks for spotting this @NishantChandla Should I assign you to fix this?

**Comment by NishantChandla** [comment]
@Evavic44 Thanks!
