### ISSUE TITLE
[FEAT] - Add profile image animation

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#114]
## Is your feature request related to a problem? Please describe.
No, I thought this will be a cool idea.

## Describe the solution you'd like
Add a simple bouncing animation on users' profile image. 

## Describe alternatives you've considered
Use CSS `@keyframe` to create an animation that translates up and down the Y-axis.

## Additional context
Nope.

**Comment by winniffy** [comment]
hi @Evavic44, should the bounce iteration be infinite?

**Comment by Evavic44** [comment]
> hi @Evavic44, should the bounce iteration be infinite?

I guess so, yes.
