### ISSUE TITLE
[FEAT] - Add comunitypro watermark

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#115]
## Is your feature request related to a problem? Please describe.
This is to ensure users can give attribution to the efforts of the community members that built this.

## Describe the solution you'd like
Add a badge on the bottom of the social icons that says **Template by Communitypro**

## Describe alternatives you've considered
1. Use badges 

<a href="https://github.com/CommunityPro/portfolio-html"><img src="https://user-images.githubusercontent.com/62628408/157202263-9174da24-b19a-4017-9b7c-a1d26ae8f014.svg"></a>

2. A stylish font
3. A button, etc.

## Additional context
None

**Comment by frankiefab100** [comment]
I will be working on this now.

**Comment by Evavic44** [comment]
Awesome, I've assigned you to it.

**Comment by Evavic44** [comment]
> Made this custom badge but can't generate the image url.

I had to download it manually. Maybe you could use this one I have already generated.

<img src="https://user-images.githubusercontent.com/62628408/157202263-9174da24-b19a-4017-9b7c-a1d26ae8f014.svg">

**Comment by frankiefab100** [comment]
Alright
