### ISSUE TITLE
[FEAT] - Add metatag guide

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#116]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Add a metatag guide for users to generate their own meta tags so when they share their portfolio to social platforms, it will preview the meta image. 

## Describe alternatives you've considered
Use [metatags.io](https://metatags.io)

## Additional context
None.

**Comment by frankiefab100** [comment]
I would like to add this.

**Comment by Evavic44** [comment]
I've assigned you to it, Frankie. ✨

**Comment by Evavic44** [comment]
Oh, snap! I forgot we added it. Thanks for spotting this @frankiefab100, Before I close this issue can you instead write a short explanation of how people can generate their metatags effectively using https://metatags.io?

**Comment by frankiefab100** [comment]
sure

**Comment by frankiefab100** [comment]
# How to generate metatags for your website.

## What are Metatags?
Metatags are tags/elements that describe the content of your website, invariably providing metadata/information for search engines.
You place them within the <head> tag above the <link> tags.

https://metatags.io makes it easy for one to generate these `metatags`.
In the top-right section, the three highlighted channels (Google, Facebook and Twitter) are most recommended.

![metags1](https://user-images.githubusercontent.com/46662771/157324276-b3177058-0a00-45af-82ff-6d3d518fd23f.jpg)

Enter the title and description of your website or project.
At the left, Preview how your website looks like when the link is searched on Google or how it appears when shared on Facebook or Twitter
See Screenshot for example.

![metatags2](https://user-images.githubusercontent.com/46662771/157324359-85c2dc95-97e7-4838-8597-4b90e5734d6e.JPG)
Then, click `Generate Meta Tags`

![metatag generated](https://user-images.githubusercontent.com/46662771/157324943-7fe07bbb-1d5d-46fd-a9a8-0fb52d1c472d.JPG)
Copy the code into the <head> tag of your `html` file.

For the preview image, upload your project image on github, cloudinary, google drive or any online storage.
the image url into `content` attribute of <meta> tags with `property="og:image"`.

#### You are good to go!

**Comment by Evavic44** [comment]
This is awesome Frankie, Since the content is much, will it be better if you create a Metatag.md file and add it there and then provide a link on the README.m ([Meta tag section](https://github.com/CommunityPro/portfolio-html#meta-tags)) saying something like: 
You can read this short tutorial on how to generate metatags for your profile.

If it's okay, go ahead and make the PR. 😎
