### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by cemmanuelonyema** [CommunityPro/portfolio-html#123]
## Mis-Alignment
The text on the hero button doesn't align well on mobile, it is left aligned instead of center

## Before
<img width="174" alt="Alignment issue" src="https://user-images.githubusercontent.com/69409465/184516421-1e113135-8b2c-404f-9134-0a64f4cdd21c.png">

## Solution - Center Alignment
The text should be centered
.
<img width="224" alt="alignment expected" src="https://user-images.githubusercontent.com/69409465/184516470-31b245af-a672-41e2-9719-3ef5e08bfcca.png">

## Desktop (please complete the following information):
 - OS: Windows
 - Browser chrome

## Smartphone (please complete the following information):**
 - Device: Andriod

 - Browser: Chrome

## Additional context
Add any other context about the problem here or do you have a recommended fix for this?

**Comment by Evavic44** [comment]
Thanks for spotting this, @cemmanuelonyema 👍🏽
