### ISSUE TITLE
[FEAT] - Add target="_blank" to external links

### ISSUE THREAD

**Issue by Deevyn9** [CommunityPro/portfolio-html#125]
## Is your feature request related to a problem? Please describe.
It's stressful when a link opens on the same tab instead of opening on a new tab.

## Describe the solution you'd like
Adding " target='_blank' " to all the links.

## Describe alternatives you've considered
The above solution should be the only solution to that issue.

## Additional context
none available

**Comment by Evavic44** [comment]
Will you like to take this up, @Deevyn9? I can assign you to it.

**Comment by Deevyn9** [comment]
Yes, i will
