### ISSUE TITLE
Typo fix - Readme file below How to Customize this Template

### ISSUE THREAD

**Issue by shubhamdev-code** [CommunityPro/portfolio-html#127]
Typo error -HTML5 semantic tags like , , 

![Screenshot 2022-12-03 022139](https://user-images.githubusercontent.com/73250851/205384284-0d90be45-a54a-4511-96ad-9b88a41f9adc.png)

**Comment by Evavic44** [comment]
> Typo error -HTML5 semantic tags like , ,
> 
> ![Screenshot 2022-12-03 022139](https://user-images.githubusercontent.com/73250851/205384284-0d90be45-a54a-4511-96ad-9b88a41f9adc.png)

Thanks for spotting this, @shubhamdev-code. Feel free to raise a PR if you have the time. 🎉

**Comment by shubhamdev-code** [comment]
Thanks @Evavic44 for assigning. I have raised a PR, hope that fix works!!
