### ISSUE TITLE
[BUG] - forthebadge.com is down due to which few badges don't load.

### ISSUE THREAD

**Issue by PriyansuMaurya** [CommunityPro/portfolio-html#146]
## Describe the bug

badges such as 

1. `built-by-developers.svg`
2. `built-with-love.svg`
3. `ctrl-c-ctrl-v.svg">`
4. `open-source.svg`

don't show up because `forthebadge.com` is down.

## Screenshots
![image](https://github.com/CommunityPro/portfolio-html/assets/101447544/896ef05f-1b78-42a5-a56f-750232b54ec6)

## Desktop (please complete the following information):
 - OS: Windows
 - Browser: Edge
 - Version: 10

## Additional context
I think would we should the changes the source to more reliable one.

**Comment by Evavic44** [comment]
Thanks for reporting this issue @PriyansuMaurya. If you know any reliable source, please raise a PR. 👍🏾

**Comment by PriyansuMaurya** [comment]
Yeah, sure. Just assign it to me,
