### ISSUE TITLE
[FEAT] - closing related issues when a pull request is closed

### ISSUE THREAD

**Issue by PriyansuMaurya** [CommunityPro/portfolio-html#148]
## Is your feature request related to a problem? Please describe.

My pull request was close but the related issue was open. so I had to manually close it.

I would like to add a GitHub Actions to automate the process of closing related issues when a pull request is closed or merged.

## Describe the solution you'd like

 GitHub Actions workflow YAML file.

`/.github/workflows/close-related-pr-issue.yml`

**Comment by Evavic44** [comment]
Hey, @PriyansuMaurya. 🙂 The `closes #<commit-id>` command already simplifies this process so it's best not to reinvent the wheel for something with an already good enough solution, but I'm happy you suggested it. Thanks.

**Comment by PriyansuMaurya** [comment]
> Hey, @PriyansuMaurya. 🙂 The `closes #<commit-id>` command already simplifies this process; it's best not to reinvent the wheel for something that already has a good enough solution. But I'm happy you suggested it. Thanks.

I didn't know that. Thanks for sharing.

can you provide an example?
