### ISSUE TITLE
[BUG] - Directly link sponsor to the Sponsor/Support Button

### ISSUE THREAD

**Issue by frankiefab100** [CommunityPro/portfolio-html#20]
**Description**
In the introductory section of the README that reads:
`This project is made from the tireless efforts of the community, so feel free to support our work by contributing, staring ✨ the project or sponsoring us. 🙏🏽`

The text **sponsoring** should redirect a user to the Sponsor button.

**Comment by Mannuel25** [comment]
I'll love to work on this @frankiefab100 / @Evavic44  , kindly assign this to me. Thanks
