### ISSUE TITLE
[FEAT] - Add transition on button class

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#52]
Add a short transition to the `btn` class so when a user hovers over the button, the hover transitions smoothly.

**Comment by Labheshm11** [comment]
I would like to work on this issue.
Would you assign this issue to me?

**Comment by Evavic44** [comment]
Sure @Labheshm11 👍🏾

**Comment by vermilion4** [comment]
are you still doing this? @Labheshm11

**Comment by ogbeidebest** [comment]
please can i take up this issue?
