### ISSUE TITLE
[BUG] - Navigation transparent on mobile view

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#59]
## Describe the bug
The navigation is transparent on mobile view and the text can be seen behind when the hamburger menu is clicked.

## To Reproduce
1. Go to the website: https://cpro-portfolio-html.netlify.app/
2. Reduce the browser view
3. Click the hamburger menu button
4. See the transparent `nav-menu`

## Expected behavior
The navigation menu should not be transparent.

## Screenshots
![transparent-navigation](https://user-images.githubusercontent.com/62628408/150532430-79c7e3be-a49c-4b95-bbfd-5963ce085901.png)

## Desktop (please complete the following information):
Windows

## Smartphone (please complete the following information):**
 - Device: iPhone 7

## Recommended fix
Add a background to the navigation menu.
This menu is controlled by the `nav-menu` class, therefore on the `style.css` file, add the primary background using the `--bg-primary variable`

```css
.navbar .nav-menu {
  background: var(--bg-primary);
}
```

**Comment by adi611** [comment]
Please assign me this issue.

**Comment by architsinghal-mriirs** [comment]
Hi. In the css class please try by adding a background : 

@media (max-width: 670px)
.nav-menu.active {
    right: 20px;
    background: white;
}

**Comment by Evavic44** [comment]
> Please assign me this issue.

Awesome work. Thanks for the PR. 👍🏾

**Comment by Evavic44** [comment]
> Hi. In the css class please try by adding a background :
> 
> @media (max-width: 670px) .nav-menu.active { right: 20px; background: white; }

Hello, @architsinghal-mriirs this issue has been fixed. 🙂 If you have any feature you want to add to this project, you can raise another issue so we discuss it further. Thanks. 👍🏾

**Comment by adi611** [comment]
> > Please assign me this issue.
> 
> Awesome work. Thanks for the PR. 👍🏾

Thanks for guiding me.
