### ISSUE TITLE
[BUG] - Add Padding To Content

### ISSUE THREAD

**Issue by vermilion4** [CommunityPro/portfolio-html#63]
## Describe the bug
The contents on the page are too squished and should be spaced out a bit.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'https://cpro-portfolio-html.netlify.app/'
2. See the contents on the main page

## Expected behaviour
It is hard to read content as they all appear to be on the same spot with no room to breathe.

## Screenshots
![Screenshot (355)](https://user-images.githubusercontent.com/49479307/150599168-3a26dc8d-f72f-4467-bceb-3212e75bdf3c.png)

## Desktop (please complete the following information):
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 97.0.4692.71

## Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 10+
 - OS: Android 11
 - Browser: Samsung Internet
 - Version: 16.0.6.23

## Additional context
Add padding or margins for the spacing.

**Comment by ogbeidebest** [comment]
i would like to work on this.. Please can I be assigned this?

**Comment by vermilion4** [comment]
sure @ogbeidebest

**Comment by ogbeidebest** [comment]
thank you

**Comment by Evavic44** [comment]
I agree @vermilion4 Thanks for raising an issue to fix this. @ogbeidebest I have assigned you, so go ahead and push a fix for this.

**Comment by vermilion4** [comment]
Welcome @Evavic44 and @ogbeidebest

**Comment by winniffy** [comment]
hi @ogbeidebest are you working on this? or can i go ahead and work on it? 😑

**Comment by manishbajagai2** [comment]
hi @Evavic44 can i work on the above issue

**Comment by Evavic44** [comment]
Sure, go ahead.

**Comment by manishbajagai2** [comment]
thank you @Evavic44

**Comment by vermilion4** [comment]
this has still not been done, the button transition as well

**Comment by Evavic44** [comment]
Yeah, closed by a mistake. Re-opening it now. 

As for the transition, it has been added and merged.

**Comment by Evavic44** [comment]
@manishbajagai2 If you need any help fixing this conflict, do let me know. We could go on a call and brainstorm. 🙏🏽

**Comment by Evavic44** [comment]
This issue is now open for anyone to fix.

**Comment by ogbeidebest** [comment]
can i take up this issue please?

**Comment by Evavic44** [comment]
Sure @ogbeidebest. Assigned

**Comment by ogbeidebest** [comment]
thanks boss
