### ISSUE TITLE
[FEAT] - Generate Meta Tags

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#65]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Generate Meta Tags for the template. 

## Describe alternatives you've considered
Use https://metatags.io/ to generate it, copy the tags generated and paste it into the head of the `html` page

## Additional context
This issue will be broken down into smaller issues so it will be easier to review and fix. Check the box as you fix any of the issues stated below.

### Image
![Portfolio Preview](https://user-images.githubusercontent.com/62628408/150613765-05924614-82f9-48f4-bbae-55135471c479.png)

### Title
Portfolio Template - Open source

### Description
Build or customize your portfolio website using this super easy template. Free to use if you are a member of the community or a contributor to this project

- [x] Update the images src with this link. Use: `https://user-images.githubusercontent.com/62628408/150613011-b78a7f5a-0af1-4312-aab0-0022e7258693.png`
- [x] Paste it in the head of the `html` page

**Comment by Evavic44** [comment]
![meta](https://user-images.githubusercontent.com/62628408/150615096-35e14c8f-5385-42c9-83fe-e1a6419a0216.png)

**Comment by vermilion4** [comment]
can i work on this?

**Comment by Evavic44** [comment]
Sure @vermilion4 Assigned. 🙌🏾
