### ISSUE TITLE
[FEAT] - Add Fontawesome link

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#68]
## Describe the solution you'd like
Add fontawesome link to the head of the page.

## Describe alternatives you've considered
This will help to use icons like the arrow icon on the resume button.

## Additional context
Get fontawesome link from: https://fontawesome.com/
Copy the minified version. 

Have issues with Fontawesome, use https://cdnjs.com/ search for fontawesome, copy the minified version and add it inside the head of the `html` file.

**Comment by vermilion4** [comment]
I have come again... can I work on it?

**Comment by Evavic44** [comment]
Omen! 😅😅 I've assigned you to fix it. Will be going to bed in a few minutes.

**Comment by vermilion4** [comment]
no problem 😂
