### ISSUE TITLE
[FEAT] - Rotate Arrow Icon

### ISSUE THREAD

**Issue by vermilion4** [CommunityPro/portfolio-html#70]
## Is your feature request related to a problem? Please describe.
The arrow icon attached to the resume button on the navbar is pointing in a direction different from the design

## Describe the solution you'd like
The arrow icon should point upward to the North-East direction.

## Additional context

![Screenshot (357)](https://user-images.githubusercontent.com/49479307/150620253-224115bd-0053-4437-8c7e-e4b1fd5dc409.png)

**Comment by winniffy** [comment]
hey @Evavic44, it looks like this bug is back up after the latest commits. what would be the appropriate way to fix this since this issue already exists?

**Comment by Evavic44** [comment]
> hey @Evavic44, it looks like this bug is back up after the latest commits. what would be the appropriate way to fix this since this issue already exists?

Actually this was deliberate. After adding the same icon on the see more button, it didn't look good, so I had to change it. 💯
