### ISSUE TITLE
[FEAT] - Configure Dependency

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#71]
## Describe the solution you'd like
Setup the dependency to collect users of the project.

## Describe alternatives you've considered
Still researching ways to do that. 

## Additional context
This will help curate the number of users of this project.

![dependecny](https://user-images.githubusercontent.com/62628408/150620503-6c811bc5-d5fa-4840-baec-b93c31611164.png)

**Comment by Evavic44** [comment]
👉🏾 <a href="https://github.com/arifszn/article-api">Example</a>

**Comment by vermilion4** [comment]
I think you just need to enable the dependency graph, and it seems only you can do it since only you can access the settings.

**Comment by Evavic44** [comment]
This is the message I get. @vermilion4 

![dependency-settings](https://user-images.githubusercontent.com/62628408/150635332-f718fbbe-a074-4ae7-892c-3f606675d201.png)

**Comment by vermilion4** [comment]
@Evavic44 go to settings, then on the left panel choose security and analysis, then enable dependency graph

**Comment by vermilion4** [comment]
Also we have no dependency package like package.json or package-lock.json or yarn.lock

**Comment by Evavic44** [comment]
> Also we have no dependency package like package.json or package-lock.json or yarn.lock

Can you fix that? @vermilion4

**Comment by vermilion4** [comment]
I'll research on it and get back to you

**Comment by vermilion4** [comment]
so after researching, I have come to the conclusion we do not need dependency. at least not here where we are dealing with just plain HTML, CSS and little javascript. dependencies are mostly needed for projects where packages that can be installed are being built. for example, one thing in common they have is there has to be an entry file like index.js from the package.json which basically holds what is to be installed. for this project though, what people that want to use it end up doing would be cloning.

**Comment by vermilion4** [comment]
just see it as downloading packages from npmjs.org. doing this means we want to publish said packages, but that would not work for this project due to the technologies used. @Evavic44

**Comment by vermilion4** [comment]
so the used by pops up when people download your packages. Do you get?

**Comment by vermilion4** [comment]
but i would still keep checking as there should be a way

**Comment by Evavic44** [comment]
Thank you so much for researching about it. Do let me know if you find anything new. 🌟
