### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by winniffy** [CommunityPro/portfolio-html#76]
## bug
there's a typo error.

## expected behavior
'visual design' should be corrected to 'visual designer'

## Screenshots
![Screenshot 2022-01-22 205355](https://user-images.githubusercontent.com/81039726/150653711-7588aae7-e943-436a-803c-c19d4d6eebc9.png)

**Comment by Evavic44** [comment]
Lol. Thanks for seeing that. Assigned.  👍🏾

**Comment by winniffy** [comment]
thank you. i wasn't sure if i needed to raise an issue for this kind of error 🤧

**Comment by vermilion4** [comment]
Well raising an issue is the only way to make an acceptable PR so it's fine

**Comment by Evavic44** [comment]
Sure, you did alright raising an issue, next time if you are absolutely sure it's a typo fix, go ahead and raise a PR. 🙌🏾

**Comment by winniffy** [comment]
thanks a lot for the feedback guys, @vermilion4 and @Evavic44 👍🏼
