### ISSUE TITLE
[FEAT] - 

### ISSUE THREAD

**Issue by manishbajagai2** [CommunityPro/portfolio-html#79]
## Needs little space around the elements 
The h2 text and the p text also the connect with me button looks congested. It would be nice to put around some space especially on top of texts

## I would like to add some margins
Putting some margins spreads out the elements to look clearer and elegant

## Screenshot

![image](https://user-images.githubusercontent.com/62448303/150655104-8e3e10bf-e7d0-40e7-8518-8573a2d56fe7.png)

**Comment by manishbajagai2** [comment]
@Evavic44 what's your thought on the above issue

**Comment by vermilion4** [comment]
there is an issue for that #63  ... also, please try adding titles to your issues

**Comment by Evavic44** [comment]
> @Evavic44 what's your thought on the above issue

Yeah, @manishbajagai2 as vermilion said, we already have an issue for that. But it seems it has been dormant for a while. If you are interested in fixing this issue, comment under the issue vermilion mentioned and I'll assign you to it. 👍🏾

**Comment by manishbajagai2** [comment]
oh ok 👍🏻

**Comment by Evavic44** [comment]
This issue has been marked as a duplicate so I'm closing it. 👍🏾
