### ISSUE TITLE
[FEAT] - Add footer section

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#92]
## Is your feature request related to a problem? Please describe.
No.

## Describe the solution you'd like
Add the footer section

**Comment by winniffy** [comment]
hey @Evavic44 can the footer design template be attached so we can know what to do? and also, can this be assigned to me?

thanks 🙏🏼

**Comment by Evavic44** [comment]
Thanks, @winniffy. I'm already pushing a fix for this. Might raise a few issues to complete it. 🙂

**Comment by winniffy** [comment]
> Thanks, @winniffy. I'm already pushing a fix for this. Might raise a few issues to complete it. 🙂

alright then. thanks.
